-- Insert Rice Varieties into the crops database
-- NSIC rice varieties from PhilRice

INSERT INTO crops (name, scientific_name, description, planting_season, harvest_days, water_requirements, temperature_min, temperature_max, humidity_min, humidity_max, rainfall_min, rainfall_max, ph_min, ph_max, marketability, soil_type_preference, weather_conditions) VALUES
('Rice - NSIC Rc10 (PAGSANJAN)', 'Oryza sativa', 'NSIC Rc10 (formerly PSB Rc10, PAGSANJAN) - Inbred rice variety developed by PhilRice. High-yielding inbred variety suitable for local cultivation.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr'),
('Rice - NSIC Rc27', 'Oryza sativa', 'NSIC Rc27 - Inbred rice variety developed by PhilRice. Suitable for local rice production.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr'),
('Rice - NSIC Rc216 (Tubigan 17)', 'Oryza sativa', 'NSIC Rc216 (Tubigan 17) - Inbred rice variety developed by PhilRice. High-yielding variety with good grain quality.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr'),
('Rice - NSIC Rc222 (Tubigan 18)', 'Oryza sativa', 'NSIC Rc222 (Tubigan 18) - Inbred rice variety developed by PhilRice. Suitable for wet season planting.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr'),
('Rice - NSIC Rc402 (Tubigan 36)', 'Oryza sativa', 'NSIC Rc402 (Tubigan 36) - Inbred rice variety developed by PhilRice. High-yielding inbred variety.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr'),
('Rice - NSIC Rc436 (Tubigan 37)', 'Oryza sativa', 'NSIC Rc436 (Tubigan 37) - Inbred rice variety developed by PhilRice. Suitable for local rice production.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr'),
('Rice - NSIC Rc480', 'Oryza sativa', 'NSIC Rc480 - Inbred rice variety developed by PhilRice. High-yielding inbred variety suitable for local cultivation.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr'),
('Rice - NSIC Rc534 (Salinas 29)', 'Oryza sativa', 'NSIC Rc534 (Salinas 29) - Inbred rice variety developed by PhilRice. High-yielding inbred variety often compared to Hybrids for yield performance.', 'Wet Season', 120, 'High', 20.0, 35.0, 70.0, 90.0, 1000.0, 2000.0, 6.0, 7.5, 'Local & Provincial (staple); high demand', 'Alluvial clay loam, Sta. Rita clay', 'Tropical, wet season May-Nov, dry Feb-Apr');
